Unfortunately most editors these days expect you to work with the Leiningen `project.clj` setup so you might need to use the <<Leiningen, Leiningen integration>> for them to work properly.

== Cursive

Cursive does not currently support resolving dependencies via `shadow-cljs.edn`. You can run `shadow-cljs pom` to generate a `pom.xml` and import that using the IntelliJ.

Alternatively you can create a dummy `project.clj` or use the full <<Leiningen, Leiningen integration>>.

```
(defproject your/project "0.0.0"
  :dependencies
  [[thheller/shadow-cljs "2.0.150"]]

  :source-paths
  ["src"])
```

You can run `npx shadow-cljs server` inside the Terminal provided by IntelliJ and use `Clojure REPL -> Remote` Run Configuration to connect to the provided <<nREPL, nREPL server>>.


== emacs / cider [[cider]]

https://github.com/shadow-cljs/shadow-cljs.github.io[HELP WANTED!]

The generic <<nrepl, nREPL>> instructions should provide everything required but additional config might be required.


== Proto REPL (Atom)

Proto REPL is mostly intended for Clojure development so most features do not work for ClojureScript. It is however possible to use it for simple evals.

You need to setup a couple of things to get it working.

1)  Create a `user.clj` in on of your `:source-paths`.

```clojure
 (ns user)

 (defn reset [])
```

The file must define the `user/reset` fn since Proto REPL will call that when connecting. If `user/reset` is not found it will call `tools.namespace` which destroys the running `shadow-cljs` server. We don't want that. You could do something here but we don't need to do anything for CLJS.

2) add `[proto-repl "0.3.1"]` to your `:dependencies`.

3) Configure a fixed <<nREPL, nREPL port>>

4) Start `shadow-cljs server` or `shadow-cljs watch your-build`.

5) Run the Atom Command `Proto Repl: Remote Nrepl Connection` connect to `localhost` and the port you configured

6) Eval `(shadow.cljs.devtools.api/watch :your-build)` (if you used `server` in 4)

7) Eval `(shadow.cljs.devtools.api/nrepl-select :your-build)`. The REPL connection is now in CLJS mode, meaning that everything you eval will be eval'd in JS. You can eval `:repl/quit` to get back to Clojure Mode. If you get `[:no-worker :browser]` you need to start the `watch` first.

8) Before you can eval CLJS you need to connect your client (eg. your Browser when building a `:browser` App).

9) Eval some JS, eg. `(js/alert "foo")`. If you get `There is no connected JS runtime` the client is not connected properly. Otherwise the Browser should show an alert.

== Calva (VS Code)

(Only tested with `browser` targets so far. Probably works with other targets too.)

=== Dependencies

You need VS Code and install the https://marketplace.visualstudio.com/items?itemName=cospaia.clojure4vscode#overview[Calva] extension.

Since Calva uses nRepl and Cider you need to include this dependency in `shadow-cljs.edn`:

```clojure
[cider/cider-nrepl "0.16.0"]
```

`shadow-cljs` will inject the required `cider-nrepl` middleware once it sees this dependency.

=== Connecting Calva to the REPLs 

Once that is done start your shadow app. (Using whatever build instead of `app`.):

```
$ shadow-cljs watch app
```

Once the app is loaded in the browser, and you see `JS runime connected` in the terminal where you started the app, Calva can connect to its repl. Open the project in VS Code and Calva will by default try to auto connect and prompt you with a list of builds read from `shadow-cljs.edn`. Select the right one (`:app` in this example) and Calva's Clojure and Clojurescript support is activated.

(If you already have the project open in VS Code when you start the app, issue the `clojure4vscode: connect` command.)

=== Features

Some of the things you can now do:

==== Intellisence and stuff

- Peek at definitions on hover.
- Get auto completion help.
- Navigate to definitions (`cmd-click` on Mac, might be `ctrl-click` on Windows and Linux).

==== Evaluation of the file, forms and selection

- Evaluate the file: `ctrl+alt+v enter` (This is done automatically one opening files.)
- Evaluate inline: `ctrl+alt+v e`
- Evaluate and replace them in the editor: `ctrl+alt+v r`
- Pretty print evaluation resuls: `ctrl+alt+v p`
- Send forms to the integrated terminal repls for evaluation: `ctrl+alt+v alt+e`

==== Run tests

- Run namespace tests: `ctrl+alt+v t`
- Run all tests: `ctrl+alt+v shift+t` (Really clunky in large projects so far.)
- Rerun previously failing tests: `ctrl+alt+v ctrl+t`
- Test failures are marked in the explorer and editors and listed in the Problem tab for easy access.

==== Terminal repls

- Show repl terminal: `ctrl+alt+v z`
- Switch namespace in terminal repl to that of the currently open file: `ctrl+alt+v n`
- Load current file and switch namespace in: `ctrl+alt+v alt+n`

==== Cljc files

- Switch between Clojure and Clojurescript repl `ctrl+alt+v alt+c` (or click the green `cljc/clj` button in the status bar). This determines both which repl is backing the editor and what terminal repl is being accessed, see above.
