== Using npm packages

Most npm packages will also include some instructions on how to use the actual code. The
“old” CommonJS style just has require calls which translates directly:

```js
var react = require("react");
```

```
(ns my.app
  (:require ["react" :as react]))
```

Whatever "string" parameter is used when calling require we transfer to the `:require` as-is.
The `:as` alias is up to you. Once we have that we can use the code like any other CLJS namespace!

```
(react/createElement "div" nil "hello world")
```

In `shadow-cljs`: *always use the `ns` form and whatever `:as` alias you provided.*
You may also use `:refer` and `:rename`. This is different than what `:foreign-libs`/CLJSJS does
where you include the thing in the namespace but then used a global `js/Thing` in your code.

Some packages just export a single function which you can call directly by
using `(:require ["thing" :as thing])` and then `(thing)`.

More recently some packages started using ES6 `import` statements in their examples. Those also
translate pretty much 1:1 with one slight difference related to default exports.
The following table can be used for translation:

.ES6 Import to CLJS Require
|===
|ES6 Import|CLJS Require

|`import defaultExport from "module-name";`
|`(:require ["module-name" :default defaultExport])`

|`import * as name from "module-name";`
|`(:require ["module-name" :as name])`

|`import { export } from "module-name";`
|`(:require ["module-name" :refer (export)])`

|`import { export as alias } from "module-name";`
|`(:require ["module-name" :rename {export alias}])`

|`import { export1 , export2 } from "module-name";`
|`(:require ["module-name" :refer (export1 export2)])`

|`import { export1 , export2 as alias2 , [...] } from "module-name";`
|`(:require ["module-name" :refer (export1) :rename {export2 alias2}])`

|`import defaultExport, { export [ , [...] ] } from "module-name";`
|`(:require ["module-name" :refer (export) :default defaultExport])`

|`import defaultExport, * as name from "module-name";`
|`(:require ["module-name" :as name :default defaultExport])`

|`import "module-name";`
|`(:require ["module-name"])`
|===

The `:default` option is currently only available in `shadow-cljs`, you can
https://dev.clojure.org/jira/browse/CLJS-2376[vote here] to hopefully make it standard.
You can always use `:as alias` and then call `alias/default` if you prefer to stay compatible
with standard CLJS in the meantime.

Notice that previously we were stuck using bundled code which included a lot of code we
didn’t actually need. Now we're in a better situation:
Some libraries are also packaged in ways  ways that allow you to include only the parts you need,
leading to much less code in your final build.

`react-virtualized` is a great example:

```js
// You can import any component you want as a named export from 'react-virtualized', eg
import { Column, Table } from 'react-virtualized'

// But if you only use a few react-virtualized components,
// And you're concerned about increasing your application's bundle size,
// You can directly import only the components you need, like so:
import AutoSizer from 'react-virtualized/dist/commonjs/AutoSizer'
import List from 'react-virtualized/dist/commonjs/List'
```

With our improved support we we can easily translate this to:

```
(ns my-ns
  ;; all
  (:require ["react-virtualized" :refer (Column Table)])
  ;; OR one by one
  (:require ["react-virtualized/dist/commonjs/AutoSizer" :default virtual-auto-sizer]
            ["react-virtualized/dist/commonjs/List" :default virtual-list]))
```

== Providing JS Dependencies

`shadow-cljs` supports several different ways to include native JS into your build. They are configurable via the `:js-options :js-provider` setting. Each `:target` usually sets the on appropriate for your build most often you won't need to touch this setting.

Currently there are 3 supported JS Providers:

[Horizontal]
`:require`:: Maps directly to the JS `require("thing")` function call. It is the default for all `node.js` targets since it can resolve `require` natively at runtime. The included JS is not processed in any way.
`:shadow`:: Resolves the JS via `node_modules` and includes a minified version version of each referenced file in the build. It is the default for the `:browser` target. `node_modules` sources do not go through `:advanced` compilation.
`:closure`:: Resolves similarly to `:shadow` but attempts to process all included files via the Closure Compiler CommonJS/ES6 rewrite facilities. They will also be processed via `:advanced` compilation.

.`:shadow` vs `:closure`
****
Ideally we want to use `:closure` as our primary JS Provider since that will run the entire application through `:advanced` giving us the most optimized output. In practice however lots of code available via `npm` is not compatible with the aggressive optimizations that `:advanced` compilation does. They either fail to compile at all or expose subtle bugs at runtime that are very hard to identify.

`:shadow` is sort of a stopgap solution that only processes code via `:simple` and achieves much more reliable support while still getting reasonably optimized code. The output is comparable (or often better) to what other tools like `webpack` generate.

Until support in Closure gets more reliable `:shadow` is the recommend JS Provider for `:browser` builds.
****


.Example config for using `:closure` in a `:browser` build.
```clojure
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options {:js-provider :closure}
   }}}
```

== Resolving JS Dependencies

By default `shadow-cljs` will resolve all `(:require ["thing" :as x])` requires following the `npm` convention.
This means it will look at `<project>/node_modules/thing/package.json` and follow the code from there. To
customize how this works `shadow-cljs` exposes a `:resolve` config option that lets you override how
things are resolved.

IMPORTANT: Currently only the `:shadow` and `:closure` JS Providers support custom resolving configuration. Since `:require` maps directly to JS `require` we can't influence what that does.

=== Using a CDN

Say you already have React included in your page via a CDN. You could just start using `js/React` again
but we stopped doing that for a good reason. Instead you can continue to use `(:require ["react" :as react])`
but configure how "react" resolves!

Here is a sample `shadow-cljs.edn` config for such a build:

```
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options
   {:resolve {"react" {:target :global
                       :global "React"}}}}

  :server
  {:target :node-script
   ...}}}
```

The `:app` build will now use the global `React` instance while the `:server` build continues using
the "react" npm package! No need to fiddle with the code to make this work.

=== Redirecting “require”

Some packages provide multiple “dist” files and sometimes the default one described doesn’t quite work
in `shadow-cljs`. One good example for this is "d3". Their default "main" points to "build/d3.node.js" but
that is not what we want when working with the browser. Their ES6 code runs into a bug in the Closure Compiler,
so we can’t use that. Instead we just redirect the require to some other file:

```
{...
 :builds
 {:app
  {:target :browser
   ...
   :js-options
   {:resolve {"d3" {:target :npm
                    :require "d3/build/d3.js"}}}
```

You can also just `(:require ["d3/build/d3.js" :as d3])` as well if you only care about the Browser.

=== Using local Files

You may also use :resolve to directly map to files in your project.

```
...
    {:resolve {"my-thing" {:target :file
                           :file "path/to/file.js"}}}
...
```

The `:file` is always relative to the project directory. The included file may use require or
`import/export` and those will be followed and included properly as well.

== Migrating cljsjs.*

Many CLJS libraries are still using CLJSJS packages and they would break with `shadow-cljs` since it
no longer supports `:foreign-libs`. I have a clear migration path for this and it just
requires one shim file that maps the `cljsjs.thing` back to its original npm package and
exposes the expected global variable.

For React this requires a file like `src/cljsjs/react.cljs`:

```
(ns cljsjs.react
  (:require ["react" :as react]
            ["create-react-class" :as crc]))
```

```
(js/goog.object.set react "createClass" crc)
(js/goog.exportSymbol "React" react)
```

Since this would be tedious for everyone to do manually I created the https://github.com/thheller/shadow-cljsjs[`shadow-cljsjs`]
library which provides just that. It does not include every package but I’ll keep adding
them and contributions are very welcome as well.

NOTE: The `shadow-cljsjs` library only provides the shim files. You’ll still need to
`npm install` the actual packages yourself.


