This target is meant for gathering up namespaces that contain tests (based on a filename pattern match),
and triggering a test runner. It contains a built-in runner that will automatically scan for `cljs.test`
tests and run them.

The relevant configuration options are:

[horizontal]
`:target`::    `:browser-test`
`:test-dir`::  A folder in which to output files. See below.
`:ns-regexp`:: (optional) A regular expression matching namespaces against project files. This only scans files, and
will not scan jars. Defaults to "-test$".
`:runner-ns`:: (optional) A namespace that can contain a start, stop, and init function. Defaults to
`shadow.test.browser`.

The normal `:devtools` options are supported, so you will usually create an http server to serve the files.
In general you will need a config that looks like this:

```
{...
 ;; tests are served via http://localhost:8021
 :dev-http {8021 "out/test"}
 :builds
 {:test
  {:target :browser-test
   :test-dir  "out/test"}}}
```

If you choose to supply a custom `:runner-ns`, it might look like this:

```
(ns tests.client-test-main
  {:dev/always true})

(defn start []
  ... run the tests...)

(defn stop [done]
  ; tests can be async. You must call done so that the runner knows you actually finished
  (done))

(defn ^:export init []
  (start))
```

Then in the build config add `:runner-ns tests.client-test-main`.

It just has `init`, `start`, `stop` methods. `init` will be called once on startup, `stop` will be called before any code is reloaded and `start` will be called after all code was reloaded.

TIP: `:runner-ns` is optional, just leave it out to use the default.

=== Generated output in `:test-dir`

The output includes two primary artifacts in your `test-dir` folder:

* `index.html` - If and only if there was not already an `index.html` file present. By default the generated
file loads the tests and runs `init` in the `:runner-ns`. You may edit or add a custom version that will
not be overwritten.
* `js/test.js` - The Javascript tests. The tests will always have this name. The entries for the module are
auto-generated.

Any webserver is fine, <<dev-http, :dev-http>> is just a convenient option.