= Shadow CLJS User's Guide
:author: Thomas Heller and Tony Kay
:revdate: Jan 10, 2018
:revnumber: 1.0
:lang: en
:encoding: UTF-8
:doctype: book
:source-highlighter: coderay
:source-language: clojure
:toc: left
:toclevels: 3
:sectlinks:
:sectanchors:
:leveloffset: 1
:sectnums:
:imagesdir: assets/img
:scriptsdir: js
:imagesoutdir: assets/img

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifdef::env-github[]
toc::[]
endif::[]

// TODO: Missing content
// - HUD
// - Undocumented global options
//    - http
//    - ssl
//    - cache-root
//    - open-file-command
//    - others???

= Introduction

The `shadow-cljs` compiler provides everything you need to compile your ClojureScript code with a focus on simplicity and ease of use. It augments the official ClojureScript compiler with a number of additional features and enhancements:

* Less configuration
* Deterministic build order
* More reliable NPM integration
** More likely your favorite JS library will work
* No need for build-specific source directories
* Better externs checker
* Better warning tracker
* Easier use with js projects
* Includes hot code reload
* Smart integration with `cljs.test` for the browser and CI
* The built-in development server aggressively fixes browser caching issues

== About this Book

=== Work in Progress

This is a work in progress. If you find an error, please submit a PR to fix it, or an issue with details of the problem.

=== Contributing

This source for this book is hosted on https://github.com/shadow-cljs/shadow-cljs.github.io[Github].

=== Conventions Used

There are many examples in this book. Most things used in these should be obvious from their context,
but to prevent misunderstanding it is important to know the author's intentions.

When command-line examples are given we may include BASH comments (starting with `#`), and will
usually include the standard user UNIX prompt of `$` to indicate separation of the command
from its output.

```bash
# A comment. This command lists files:
$ ls -l
shadow-cljs.edn
project.clj
...
```

Many of the examples are of the configuration file for the compiler. This file contains an EDN map.
Where we have already discussed required options we will often elide them for clarity. In this
case we'll usually include an elipsis to indicate "content that is required but isn't in our
current focus":

.Example 1. Specify dependencies
```
{:dependencies [[lib "1.0"]]}
```

.Example 2. Add source paths
```
{...
 :source-paths ["src"]
 ...}
```

This allows us to concisely include enough context to understand the nesting of the configuration of
interest:

.Example 3. Nested option
```
{...
 :builds {:build-id {...
                     :output-dir "resources/public/js"}}}
```

Code examples may are similarly shortened.


= Installation

== Standalone via `npm`

You will need:

- https://nodejs.org[`node.js`] (v6.0.0+, most recent version preferred)
- https://www.npmjs.com[`npm`] or https://www.yarnpkg.com[`yarn`]
- Java SDK (Version 8). http://openjdk.java.net/install/[OpenJDK] or http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle]

.NPM
```bash
$ npm install --save-dev shadow-cljs
$ npm install -g shadow-cljs
```

.Yarn
```bash
$ yarn add --dev shadow-cljs
$ yarn global add shadow-cljs
```

== Library

Although it is recommended to run the standalone version via `npm` you can also embed `shadow-cljs` into any other Clojure JVM tool (eg. `lein`, `boot`, ...).

The artifact can be found at:
[link=https://clojars.org/thheller/shadow-cljs]
image::https://camo.githubusercontent.com/f91298f67b2b1c7a75124738f669be1f6928e976/68747470733a2f2f696d672e736869656c64732e696f2f636c6f6a6172732f762f746868656c6c65722f736861646f772d636c6a732e737667[]

= Usage

include::usage.adoc[]

= Configuration

`shadow-cljs` is configured by a `shadow-cljs.edn` file in your project root directory. You can
create a default one by running `shadow-cljs init`. It should contain a map with some global
configuration and a `:builds` entry for all your builds.

```
{:source-paths [...]
 :dependencies [...]
 :builds {...}}
```

An example config could look like this:

```clojure
{:dependencies
 [[reagent "0.8.0-alpha2"]]

 :source-paths
 ["src"]

 :builds
 {:app {:target :browser
        :output-dir "public/js"
        :asset-path "/js"
        :modules {:main {:entries [my.app]}}}}}
```

The file structure for this example should look like this:
```text
.
├── package.json
├── shadow-cljs.edn
└── src
    └── my
        └── app.cljs
```

== Source Paths

`:source-paths` configures your JVM classpath. The compiler will use this config to find Clojure(Script) source files (eg. `.cljs`).

It is fine to put everything into one source path but you can use multiple if you want to "group" source files in certain ways. It is useful if you want to keep your tests separate for example.

.Using multiple source paths
```
{:source-paths ["src/main" "src/test"]
 ...}
```

.File Structure
```text
.
├── package.json
├── shadow-cljs.edn
└── src
    └── main
        └── my
            └── app.cljs
    └── test
        └── my
            └── app_test.cljs
```

It is not recommended to separate source files by extension (eg. `src/clj`, `src/cljs`, `src/cljc`). For some reason this is widely used in CLJS project templates but it just makes things harder to use.

== Dependencies

=== Clojure(Script)

Your dependencies are managed via the `:dependencies` key at the root of the `shadow-cljs.edn` config file. They are declared in the same notation that other Clojure tools like `lein` or `boot` use.

Notice that the source path is *only* specified once in the entire configuration. The system will use namespace dependency graphs to determine what code is needed in the final output of any given build.

=== JavaScript

`shadow-cljs` integrates fully with the https://www.npmjs.com/[`npm`] ecosystem to manage JavaScript dependencies.

You can use `npm` or `yarn` to manage your dependencies, please refer to their respective documentation.

[horizontal]
npm:: https://docs.npmjs.com/
yarn:: https://yarnpkg.com/en/docs

Almost every package available via `npm` will explain how to install it. Those instructions now apply to shadow-cljs as well.

.Installing a JavaScript package
```bash
# npm
$ npm install the-thing

# yarn
$ yarn add the-thing
```

Nothing more is required. Dependencies will be added to the `package.json` file and this will be used to manage them.

If you don’t have a `package.json` yet run `npm init` from a command line.

== Server Options

This section is for other options that configure the `shadow-cljs` server instance. They are optional.

=== nREPL [[nREPL]]

The `shadow-cljs` server provides a nREPL server via TCP. If you look at the startup message you'll see
the port of nREPL, and the port will also be stored in `target/shadow-cljs/nrepl.port`:

```bash
$ shadow-cljs watch dev
shadow-cljs - HTTP server for ":app" available at http://localhost:8020
shadow-cljs - server running at http://0.0.0.0:9630
shadow-cljs - nrepl running at /0.0.0.0:9462
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
```

You can configure the port and additional middleware with `shadow-cljs.edn`:

```
{...
 :nrepl {:port 9000
         :middleware []} ; list of namespace-qualified symbols
}
```

=== SSL

The `shadow-cljs` HTTP servers support SSL. It requires a Java Keystore that provides a matching private key and certificate.

.`shadow-cljs.edn` with SSL configured
```
{...
 :ssl {:keystore "ssl/keystore.jks"
       :password "shadow-cljs"}
 ...}
```

The above are the defaults so if you want to use those it is fine to just set `:ssl {}` to use those.

You can create a Keystore using the java `keytool` command. Creating a trusted self-signed certificate is also possible but somewhat complicated.

I used https://certsimple.com/blog/localhost-ssl-fix[this guide] to create a self-signed certificate using macOS. Importing the created `.p12` file can be turned into the required `keystore.jks` via the `keytool` utility.

```bash
$ keytool -importkeystore -destkeystore keystore.jks -srcstoretype PKCS12 -srckeystore <the-cert>.p12
```

IMPORTANT: You must generate the Certificate with a SAN (Subject Alternative Name) for "localhost" (or whichever host you want to use). SAN is required to get Chrome to trust the Certificate and now show warnings. The password used when exporting must match the password assigned to the Keystore.

// TODO: full guide, other platforms

=== HTTP(S)

The `shadow-cljs` server starts one primary HTTP server. It is used by the builds to connect the Hot Reload and REPL clients via websocket. By default it listens on Port 9630. If that Port is in use it will increment by one and attempt again until an open Port is found.

.Startup message indicating the Port used
```bash
shadow-cljs - server running at http://0.0.0.0:9630
```

When `:ssl` is configured the server will be available via `https://` instead.

TIP: The server automatically supports HTTP/2 when using `:ssl`.

The UI served by this server is still in development so the main purpose of this HTTP server currently is serving the websockets.

If you prefer to set your own port instead you can do this via the `:http` config.

.`shadow-cljs.edn` with `:http` config
```
{...
 :http {:port 12345
        :host "my.machine.local"}
 ...}
```

`:ssl` switches the server to server `https://` only. If you want to keep the `http://` version you can configure a separate `:ssl-port` as well.

```
{...
 :http {:port 12345
        :ssl-port 23456
        :host "localhost"}
 ...}
```


= Build Configuration

`shadow-cljs.edn` will also need a `:builds` section. Builds should be a map of builds *keyed* by build ID:

.A configuration file with a build map.
```
{:dependencies [[some-library "1.2.1"] ...]
 :source-paths ["src"]
 :builds
 {:app   {:target     :browser
          ... browser-specific options ...}
  :tests {:target :karma
          ... karma-specific options ...}}}
```

Each build describes artifacts that the compiler will build. The build target is an extensible feature of `shadow-cljs`, and the compiler comes with quite a few of them already.

== Build Target

Each build in `shadow-cljs` must define a `:target` which defines where you intend your code to be executed. There are default built-ins for the <<BrowserTarget,browser>> and <<NodeTarget,`node.js`>>. They all share the basic concept of having `:dev` and `:release` modes. `:dev` mode provides all the usual development goodies like fast compilation, live code reloading and a REPL. `:release` mode will produce optimized output intended for production.

Targets are covered in separate chapters.

Here are some of them:

[Horizontal]
<<target-browser, `:browser`>>:: Output code suitable for running in a web browser.
`:bootstrap`:: Output code suitable for running in bootstrapped cljs environment.
`:browser-test`:: Scan for tests to determine required files, and output tests suitable for running in the browser.
`:karma`:: Scan for tests to determine required files, and output karma-runner compatible tests. See http://karma-runner.github.io/2.0/index.html[Karma].
`:node-library`:: Output code suitable for use as a node library.
`:node-script`:: Output code suitable for use as a node script.
`:npm-module`:: Output code suitable for use as an NPM module.

Each target is covered in more detail in its own chapter since the remaining build options vary on
the target you select.


== Development Options

Each build `:target` typically provides some development support. They are grouped under the `:devtools` key for each `:build`.

=== Preloads

As a developer most of your time is spent in development mode. You're probably familiar with tools like `figwheel`,
`boot-reload`, and `devtools`. It's almost certain that you want one or more of these in your builds.

Preloads are used to force certain namespaces into the front of your generated Javascript. This is
generally used to inject tools and instrumentation before the application actually loads and runs. The
preloads option is simply a list of namespaces in the `:devtools`/`:preloads` section of
`shadow-cljs-edn`:

```
{...
 :builds
 {:app {...
        :devtools {:preloads [fulcro.inspect.preload]
                   ...}}}}
```

NOTE: Since version 2.0.130 shadow-cljs automatically adds "binaryage/cljs-devtools" to the preloads in
`watch` and `compile` if they are on the classpath. All you need to do is make sure it is in your
`dependencies` list.

=== Hot Code Reload

The React and ClojureScript ecosystems combine to make this kind of thing super useful. The `shadow-cljs`
system includes everything you need to do your hot code reload, without needing to resort to external tools.

In order to use it you simply run:

```
shadow-cljs watch build-id
```

=== Lifecycle Hooks

The build configuration supports hooks that allow you to run functions just before hot code reload
brings in updated code, and just after. These are useful for stopping/starting things that would otherwise
close over old code. The options go in the `:devtools` section of the build config and are:

[Horizontal]
`:before-load`:: A symbol (with namespace) of a function to run just before refreshing
files that have been recompiled.  This function *must* by synchronous in nature.
`:before-load-async`:: A symbol (with namespace) of a function `(fn [done] )` to run just before refreshing. This function
can do async processing, but *must* call `(done)` to indicate it is complete.
`:after-load`:: A symbol (with namespace) of a function to run after hot code reload is complete.

.A sample of lifecycle hooks.
```
{...
 :builds
 {:app {...
        :devtools {:before-load  my.app/stop
                   :after-load   my.app/start
                   ...}}}}
```

= Targeting the Browser [[target-browser]]

include::target-browser.adoc[]

= Targeting node.js

There is built-in support for generating code that is intended to be use as a stand-alone
script, and also for code that is intended to be used as a library. See the
section on <<CommonConfig,common configuration>> for the base settings needed in
a configuration file.

NOTE: The optimizations in node at the time of this writing default to `:simple`.
You can use the normal configuration options to set the <<Optimization, optimization level>>.

== node.js Scripts [[target-node-script]]

include::target-node-script.adoc[]

== node.js Libraries [[target-node-library]]

include::target-node-library.adoc[]

== Creating `npm` packages

// TODO: Thomas: I think it would be useful to show a package.json and a little bit of an example
// on how you could set up to deploy this on NPM.

= Embedding in the JS Ecosystem -- The `:npm-module` Target [[target-npm-module]]

include::target-npm-module.adoc[]

= Testing

`shadow-cljs` provides a few ultility targets to make building tests a little easier.

== Browser Test [[target-browser-test]]

include::target-browser-test.adoc[]

== Targeting Tests to Karma for Continuous Integration [[target-karma]]

include::target-karma.adoc[]

= Custom Targets

include::target-custom.adoc[]

= JavaScript Dependencies [[js-deps]]

include::js-deps.adoc[]

= Generating Production Code -- All Targets

include::release.adoc[]

= Editor/IDE/REPL Setup

include::editor-integration.adoc[]

= What to do when things don’t work?

Since the JS world is still evolving rapidly and not everyone is using the same way to write and
distribute code there are some things `shadow-cljs` cannot work around automatically. These
can usually be solved with custom `:resolve` configs, but there may also be bugs or oversights.

If you cannot resolve such an issue with the instructions in this chapter, then try asking on the
https://clojurians.slack.com/messages/C6N245JGG[`#shadow-cljs` Slack channel].

= Hacking

== Patching Libraries

The `shadow-cljs` compiler ensure that things on your source paths are compiled first, overriding files from JARs. This means that you can copy a source file from a library, patch it, and include it in your own source directory.

This is a convenient way to test out fixes (even to `shadow-cljs` itself!) without having to clone
that project and understand its setup, build, etc.
